# Default values for Fn
imagePullPolicy: IfNotPresent

fn:
  service:
    port: 80
    type: LoadBalancer
    annotations: {}
  controlPlaneEndpoint: http://please-insert-full-external-api-endpoint
  workPlaneEndpoint: http://please-insert-full-external-runner-endpoint


fnserver:
  image: fnproject/fnserver:0.3.227  #TAG-fnserver-image
  logLevel: info
  resources: {}
  nodeSelector: {}
  tolerations: []


ui:
  enabled: true
  fnui:
    image: fnproject/ui:0.0.21  #TAG-fnui-image
    resources: {}
  flowui:
    image: fnproject/flow:ui #TAG-flowui-image
    resources: {}
  service:
    flowuiPort: 3000
    fnuiPort: 4000
    type: LoadBalancer
    annotations: {}


flow:
  image: fnproject/flow:0.1.75  #TAG-flow-image
  logLevel: info
  service:
    port: 80
    type: ClusterIP
    annotations: {}
  resources: {}


##
## MySQL chart configuration
##
mysql:
  persistence:
    enabled: false
    nodeSelector: mysql-storage
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    storageClass: mysql
    accessMode: ReadWriteOnce
    size: 8Gi

  mysqlDatabase: fndb
  mysqlUser: fnapp
  mysqlPassword: boomsauce

##
## Redis chart configuration
##
redis:
  persistence:
    enabled: false
    nodeSelector: redis-storage
    storageClass: redis
    accessMode: ReadWriteOnce
    size: 8Gi
  usePassword: true
  redisPassword:

## Ingress configuration.
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
