version: 2

jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - run:
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo bash
      - run:
          command: |
            sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
      - run:
          command: |
            sudo minikube update-context
            sudo chown -R circleci:circleci $HOME/.kube $HOME/.minikube
      - run:
          command: |
            JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until sudo kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
      - run:
          command: |
            sudo add-apt-repository -y  ppa:duggan/bats
            sudo apt-get update
            sudo apt install bats socat util-linux
            docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
      - run:
          command: |
            sudo kubectl cluster-info
      - run:
          command: |
            helm init
      - run:
          command: |
            kubectl get all --all-namespaces
      - run:
          command: |
            helm dep build fn
            bats tests
