version: 2

jobs:
  build:
    steps:
      - checkout
      - run:
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo bash
      - run:
          command: |
            helm lint fn


