{{- if eq .Values.tls.enabled true }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.default_issuer_name }}
spec:
  acme:
    server: {{ .Values.tls.server }}
    email: {{ .Values.tls.acme_registration_email }}
    privateKeySecretRef:
      name: {{ .Values.tls.secret_reference }}
    http01: {}
{{- end -}}
