apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-flow-depl
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: flow-service
    spec:
      containers:
        - name: flow
          image: {{ .Values.flow.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
          - name: LISTEN
            value: :8081
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: mysql-password
          - name: DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: DB_URL
            value: mysql://fnapp:$(DB_PASSWD)@tcp($(DB_HOST):3306)/fndb
          - name: API_URL
            value: http://{{ template "fullname" . }}-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-flowui
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: fn-service
    spec:
      containers:
        - name: flow-ui
          image: {{ .Values.flowui.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://{{ template "fullname" . }}-api
            - name: COMPLETER_BASE_URL
              value: http://{{ template "fullname" . }}-flow
