apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-flow
  labels:
    app: {{ template "fullname" . }}
    role: flow-svc
spec:
  type: LoadBalancer
  ports:
    - name: flow
      port: 8081
      targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    role: flow-server
