apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-flow-depl
  labels:
    app: {{ template "fullname" . }}
    role: flow-depl
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         role: flow-server
    spec:
      containers:
        - name: flow
          image: fnproject/flow:latest
          ports:
            - containerPort: 8081
          env:
          - name: LISTEN
            value: :8081
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: mysql-password
          - name: DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: DB_URL
            value: mysql://fnapp:$(DB_PASSWD)@tcp($(DB_HOST):3306)/fndb
          - name: API_URL
            value: http://{{ template "fullname" . }}-api:8080

