apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-flow
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: flow
      port: 80
      targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    role: flow-service