apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: fn
        role: fn-node
    spec:
      containers:
      - name: fn-service
        image: fnproject/fnserver:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql
              key: mysql-password
        - name: DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: DB_URL
          value: mysql://root:$(DB_PASSWD)@tcp($(DB_HOST):3306)/fn