apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: fn-service
        image: fnproject/fnserver:latest
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /v1/apps
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: PORT
          value: "80"
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql
              key: mysql-password
        - name: DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: DB_URL
          value: mysql://fnapp:$(DB_PASSWD)@tcp($(DB_HOST):3306)/fndb
        - name: MQ_HOST
          value: {{ .Release.Name }}-redis
#  TODO:
#        - name: MQ_PASSWD
#          valueFrom:
#            secretKeyRef:
#              name: {{ .Release.Name }}-redis
#              key: redis-password
        - name: MQ_URL
          value: redis://$(MQ_HOST):6379/
