apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    role: fn-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: LoadBalancer
  ports:
  - name: fn
    port: {{ .Values.fn.externalPort}}
    targetPort: 8080
  selector:
    app: {{ template "fullname" . }}
    role: fn-node