apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.fn.service.annotations }}
  annotations:
{{ toYaml .Values.fn.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.fn.service.type }}
  ports:
  {{- if .Values.fnserver.splitWorkers }}
  # In a split workers scenario this service targets the api nodes only and directly.
  - name: fn
    port: {{ .Values.fn.service.port }}
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}
    role: fn-service
  {{- else }}
  # In the normal scenario this service goes through the fnlb.
  - name: fn
    port: {{ .Values.fn.service.port }}
    targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    role: fn-lb
{{- end }}

{{- if .Values.fnserver.splitWorkers }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-runner
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.fn.service.annotations }}
  annotations:
{{ toYaml .Values.fn.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.fn.service.type }}
  # Calls to the runners always go through the fnlb.
  ports:
  - name: fn
    port: {{ .Values.fn.service.port }}
    targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    role: fn-lb
{{- end }}