apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    role: fn-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: LoadBalancer
  ports:
  - name: fn
    port: {{ .Values.fn.externalPort}}
    targetPort: {{ .Values.fn.externalPort}}
  - name: fn-ui
    port: {{ .Values.fnui.externalPort}}
    targetPort: {{ .Values.fnui.externalPort}}
  selector:
    app: {{ template "fullname" . }}
    role: fn-service