apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: fn
    port: {{ .Values.fn.externalPort}}
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}
