# Default values for Fn
imagePullPolicy: IfNotPresent

fn:
  service:
    port: 80
    type: LoadBalancer
    annotations: {}
  controlPlaneEndpoint: http://please-insert-full-external-api-endpoint
  workPlaneEndpoint: http://please-insert-full-external-runner-endpoint

fnlb:
  image: fnproject/fnlb:0.0.189

fnserver:
  image: fnproject/fnserver:0.3.227  #TAG-fnserver-image
  logLevel: info
  resources: {}
  nodeSelector: {}
  tolerations: []


## Ingress configuration.
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: false
